In [11]:
# Dependencies
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
makes = ["ford", "toyota", "chevrolet"]

In [16]:
for make in makes:
        url = f"https://vpic.nhtsa.dot.gov/api/vehicles/getmodelsformake/{make}?format=json"
        response = requests.get(url)
        if response.status_code == 200:
                data = response.json()
                print(f"Data for {make}:")
                for model in data['Results']:
                        print(f"Model: {model['Model_Name']}")
        else:
                print(f"Failed to retrieve data for {make}")

Data for ford:
Model: Crown Victoria
Model: Focus
Model: Fusion
Model: Mustang
Model: Taurus
Model: E-150
Model: Edge
Model: Escape
Model: Expedition
Model: Explorer
Model: F-150
Model: Flex
Model: Ranger
Model: Explorer Sport Trac
Model: F-250
Model: F-350
Model: F-450
Model: F-550
Model: F-650
Model: F-750
Model: Transit Connect
Model: E-250
Model: E-350
Model: E-450
Model: Expedition MAX
Model: Thunderbird
Model: GT
Model: Five Hundred
Model: Excursion
Model: Freestyle
Model: Freestar
Model: Motorhome Chassis
Model: Taurus X
Model: Fiesta
Model: Commercial Chassis
Model: C-Max
Model: Transit
Model: Affordable Aluminum
Model: Eagle Ford Tanks & Trailers LLC
Model: Escort
Model: ZX2
Model: Windstar
Model: E-550
Model: B-750
Model: F-800
Model: Explorer Sport
Model: Milford Welding & Manufacturing Inc.
Model: Aspire
Model: Probe
Model: Contour
Model: Bronco
Model: Aerostar
Model: F-150 Heritage
Model: Waterford Tank and Fabrication, LTD
Model: Milford Pipe & Supply
Model: L8501
Model: LT8501
Model: L9501
Model: LT9501
Model: L8511
Model: LT8511
Model: L9511
Model: LT9511
Model: L8513
Model: LT8513
Model: L9513
Model: LT9513
Model: L9522
Model: LT9522
Model: A8513
Model: AT8513
Model: A9513
Model: AT9513
Model: A9522
Model: AT9522
Model: B800
Model: F-Super Duty
Model: F-700
Model: P700
Model: P800
Model: FT900
Model: L8000
Model: L9000
Model: LL9000
Model: LLA9000
Model: LLS9000
Model: LS8000
Model: LS9000
Model: LT8000
Model: LT9000
Model: LTS8000
Model: LTS9000
Model: LTL9000
Model: LTLA9000
Model: LTLS9000
Model: LA8000
Model: LA9000
Model: LTA9000
Model: LN7000
Model: LN8000
Model: LN9000
Model: LNT8000
Model: LNT9000
Model: CF8000
Model: CFT8000
Model: CF7000
Model: Fords Trailer Sales
Model: Festiva
Model: Low Cab Forward
Model: Tempo
Model: B600
Model: B700
Model: F-600
Model: Recreational Vehicle
Model: F-590
Model: P600
Model: CL9000
Model: CLT9000
Model: Bronco II
Model: FT800
Model: CT8000
Model: C800
Model: C8000
Model: Laser
Model: LTD
Model: Fairmont
Model: Granada
Model: Travel Park
Model: '34
Model: CF6000
Model: 1500 Foldaway
Model: B7000
Model: C7000
Model: F7000
Model: F8000
Model: FT8000
Model: Courier
Model: B6000
Model: C600
Model: C700
Model: F6000
Model: LN600
Model: LN700
Model: L800
Model: LT800
Model: LN800
Model: LNT800
Model: E-100
Model: F-100
Model: CT800
Model: Swinford Mfg
Model: Ecosport
Model: CRANFORD RADIATOR INC.
Model: Bradford Built
Model: Malibu Sedan
Model: Cordova Sedan
Model: Classic Sedan
Model: Bradford #1
Model: Stafford's Trailers
Model: Medford Steel
Model: Expedition EL
Model: Affordable Trailers
Model: Bronco Sport
Model: Mustang Mach-E
Model: Maverick
Model: GT MKII
Model: Mustang GTD
Data for toyota:
Model: Scion xA
Model: Scion tC
Model: Corolla
Model: Prius
Model: Scion xB
Model: Land Cruiser
Model: Highlander
Model: 4-Runner
Model: RAV4
Model: Tacoma
Model: Scion FR-S
Model: FJ Cruiser
Model: Yaris
Model: Avalon
Model: Corolla Matrix
Model: Tundra
Model: Sienna
Model: Camry
Model: Camry Solara
Model: Sequoia
Model: Scion xD
Model: Venza
Model: FCHV-adv
Model: Tercel
Model: Celica
Model: Supra
Model: MR2
Model: Paseo
Model: Echo
Model: Cressida
Model: Cargo Van
Model: Previa
Model: T100
Model: Mirai
Model: Scion iQ
Model: Scion iM
Model: 86
Model: Scion iA
Model: Prius V
Model: Prius C
Model: Prius Plug-in
Model: Pick-Up
Model: Van
Model: Starlet
Model: Corona
Model: COROLLA iM
Model: C-HR
Model: Prius Prime
Model: Yaris iA
Model: RAV4 Prime
Model: Corolla Cross
Model: GR86
Model: bZ4X
Model: Crown
Model: GR Corolla
Model: Grand Highlander
Model: Crown Signia
Data for chevrolet:
Model: Aveo
Model: Camaro
Model: Caprice Police Vehicle
Model: Corvette
Model: Cruze
Model: Impala
Model: Malibu
Model: Sonic
Model: Spark
Model: SS
Model: Volt
Model: Captiva Sport
Model: Equinox
Model: Express
Model: Orlando
Model: Silverado
Model: Suburban
Model: Tahoe
Model: Traverse
Model: Tracker
Model: City Express
Model: Geo Prizm
Model: Avalanche
Model: Matiz
Model: Colorado
Model: Cobalt
Model: Optra
Model: Kalos
Model: Trailblazer
Model: HHR
Model: Uplander
Model: W4
Model: W5
Model: Monte Carlo
Model: SSR
Model: Epica
Model: Cavalier
Model: U100
Model: 3 ton
Model: Astro Van
Model: Venture
Model: B7
Model: Lumina
Model: Alero
Model: Caprice
Model: Corsica
Model: Beretta
Model: Hearse/Limo
Model: Metro
Model: GMT-400
Model: Military Truck
Model: Forward Control
Model: Trax
Model: S-10 Pickup
Model: C/K Pickup
Model: P - Series
Model: Lumina APV
Model: Blazer
Model: Impala Limited
Model: Bolt EV
Model: 3500HD
Model: 5500HD
Model: 3500 / 4500
Model: 4500HD
Model: 4500XD
Model: 5500XD
Model: T-Series
Model: C4
Model: C5
Model: C6
Model: C7
Model: C8
Model: W7
Model: Hearse/Limo Commercial Chassis
Model: W3
Model: W6
Model: D7
Model: P6S
Model: S-10 Blazer
Model: P Truck Forward
Model: Celebrity
Model: Geo Spectrum
Model: G-Series
Model: Cutaway Chassis
Model: Motorhome Chassis
Model: Chevette
Model: Hi-Cube
Model: Cutaway Van
Model: S7
Model: Geo Sprint
Model: Nova
Model: S6
Model: R Conventional
Model: V Conventional
Model: Citation
Model: Bus Chassis
Model: Heavy Conventional
Model: Aluminum Tilt
Model: El Camino
Model: LUV
Model: Malibu Classic
Model: 3500
Model: 4500
Model: Bolt Incomplete
Model: FTR / 6500XD
Model: 6500XD
Model: Silverado HD
Model: Silverado LD
Model: 7500XD
Model: W3500/W4500
Model: W5500/W5500 HD
Model: Onix
Model: Silverado LTD
Model: Bolt EUV
Model: 3500HG
Model: 4500HG
Model: 5500HG
Model: 5500XG
Model: Blazer EV
Model: Silverado EV
Model: Equinox EV
Model: Traverse Limited
Model: Cruze Limited
Model: Malibu Limited
Model: BrightDrop 400
Model: BrightDrop 600
Model: BrightDrop 400, BrightDrop 600
Model: Suburban HD

In [10]:
vehicles_data_df = pd.DataFrame(vehicles_data)
vehicles_data_df.head()

   ModelYear    Make         Model  VehicleId
0       2024  TOYOTA       4RUNNER          0
1       2024  TOYOTA          BZ4X          0
2       2024  TOYOTA         CAMRY          0
3       2024  TOYOTA  CAMRY HYBRID          0
4       2024  TOYOTA       COROLLA          0

In [7]:
url = "https://api.nhtsa.gov//SafetyRatings/VehicleId/19438?format=json"
response = requests.get(url)
if response.status_code == 200:
    data = response.json()
else:
    print("Failed to retrieve data. Status code:", response.status_code)
    data = {}
if 'Results' in data:
    prius_data = data['Results']
else:
    print("No 'Results' found in data.")
    prius_data = []

In [8]:
prius_df = pd.DataFrame(prius_data)
prius_df.head()

,VehiclePicture,OverallRating,OverallFrontCrashRating,FrontCrashDriversideRating,FrontCrashPassengersideRating,FrontCrashPicture,FrontCrashVideo,OverallSideCrashRating,SideCrashDriversideRating,SideCrashPassengersideRating,...,NHTSAForwardCollisionWarning,NHTSALaneDepartureWarning,ComplaintsCount,RecallsCount,InvestigationCount,ModelYear,Make,Model,VehicleDescription,VehicleId
0,https://static.nhtsa.gov/images/vehicles/BTL_5...,5,5,5,5,https://static.nhtsa.gov/crashTest/images/2024...,https://static.nhtsa.gov/crashTest/videos/2024...,5,5,5,...,Standard,Standard,10,2,0,2024,TOYOTA,PRIUS,2024 Toyota PRIUS 5 HB AWD,19438